2024-07-03 13:49:39,466 - src.utils - INFO - Configuration loaded from config/config.yaml
2024-07-03 13:49:39,606 - src.cloud_functions - INFO - System time updated successfully
2024-07-03 13:49:39,606 - src.utils - ERROR - Error loading sensor metadata from sensor_mapping.yaml: [Errno 2] No such file or directory: 'sensor_mapping.yaml'
2024-07-03 13:49:39,606 - src.utils - ERROR - An error occurred in the main process: [Errno 2] No such file or directory: 'sensor_mapping.yaml'
Traceback (most recent call last):
  File "/home/bryan/Desktop/Logger_Lora/main.py", line 37, in main
    sensor_metadata = load_sensor_metadata(config["sensor_metadata"])
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bryan/Desktop/Logger_Lora/src/utils.py", line 73, in load_sensor_metadata
    with open(sensor_file, 'r') as f:
         ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'sensor_mapping.yaml'
